version: "3.9"

services:
  pg_master:
    image: postgres:15
    container_name: pg_master
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: testDB
    ports:
      - "5432:5432"
    volumes:
      - pg_master_data:/var/lib/postgresql/data
    command: >
      postgres -c wal_level=logical
               -c max_wal_senders=10
               -c max_replication_slots=10

  pg_replica:
    image: postgres:15
    container_name: pg_replica
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: testDB
    ports:
      - "5433:5432"
    volumes:
      - pg_replica_data:/var/lib/postgresql/data

volumes:
  pg_master_data:
  pg_replica_data:
