// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package db

import (
	"time"
)

type Order struct {
	ID          int32
	ProductName string
	Quantity    int32
	OrderDate   time.Time
}
