// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: query.sql

package db

import (
	"context"
	"time"
)

const insertOrder = `-- name: InsertOrder :one
INSERT INTO orders(product_name, quantity, order_date)
VALUES ($1, $2, $3)
RETURNING id, product_name, quantity, order_date
`

type InsertOrderParams struct {
	ProductName string
	Quantity    int32
	OrderDate   time.Time
}

func (q *Queries) InsertOrder(ctx context.Context, arg InsertOrderParams) (Order, error) {
	row := q.db.QueryRowContext(ctx, insertOrder, arg.ProductName, arg.Quantity, arg.OrderDate)
	var i Order
	err := row.Scan(
		&i.ID,
		&i.ProductName,
		&i.Quantity,
		&i.OrderDate,
	)
	return i, err
}

const listOrder = `-- name: ListOrder :many
SELECT id, product_name, quantity, order_date
FROM orders
ORDER BY Id
`

func (q *Queries) ListOrder(ctx context.Context) ([]Order, error) {
	rows, err := q.db.QueryContext(ctx, listOrder)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Order
	for rows.Next() {
		var i Order
		if err := rows.Scan(
			&i.ID,
			&i.ProductName,
			&i.Quantity,
			&i.OrderDate,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
